<?php
/** @var \Magento\Customer\Block\Account\AuthenticationPopup $block */
?>
 <?php $helper = $this->helper('Smarty\Zarpoo\Helper\Data'); ?>
 <?php if(!$helper->isLoggedIn()) : ?>
    <div id="ajaxlogin-popup" data-bind="scope:'ajaxLogin'" style="display: none;">
    <script>
        window.ajaxLogin = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
    </script>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#ajaxlogin-popup": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
</div>
<?php endif; ?>